project:
  type: website
  output-dir: docs
  
website:
  title: "Taylor Swift Songs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

