project:
  type: website
  output-dir: docs
  
website:
  title: "Alicia's webpage"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: Storyboard

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual


